### ISSUE TITLE
UX Improvement on Index page

### ISSUE THREAD

**Issue by kishankr7979** [GP-Kulam/link-manager#17]
**Is your feature request related to a problem? Please describe.**
----
- Add Pointer cursor when hovered on Student/Teacher selection or continue button in Index page

**Describe the solution you'd like**
----
- A simple CSS will do the Job

**Comment by kishankr7979** [comment]
@GP-Kulam @sixthcodebrewer Please Assign me this issue, as it will improve the User Experience

**Comment by sixthcodebrewer** [comment]
Cool
