### ISSUE TITLE
Improving the UI of the login page

### ISSUE THREAD

**Issue by sixthcodebrewer** [GP-Kulam/link-manager#2]
The login page UI must be improved.

**Comment by rabsonj** [comment]
Hi! Can you please assign me this issue

**Comment by kalpikha** [comment]
hey I've resolved this, but I'm unable to tackle this error.
"ERROR: Permission to .git denied to user"

**Comment by rabsonj** [comment]
![gitError](https://user-images.githubusercontent.com/52573181/107663685-f153ff80-6c8b-11eb-9c2b-beb3664ef225.PNG)

Try that solution. I hope it works out

**Comment by Amool-kk** [comment]
what is particular issues in login page UI

**Comment by kalpikha** [comment]
> what is particular issues in login page UI

There isn't one.
just improved the design of login page

**Comment by sixthcodebrewer** [comment]
> > what is particular issues in login page UI
> 
> There isn't one.
> just improved the design of login page

Will merge your pull request.

**Comment by sixthcodebrewer** [comment]
> what is particular issues in login page UI

You can take a look by running the project

**Comment by tinchods93** [comment]
Hello! I would like to work on this issue! 
It would be my first time working with someone elses project, but i think i can help you.

**Comment by tinchods93** [comment]
Hello! I would like to work on this issue! 
It would be my first PR and also my first time working with someone elses project, but i think i can help you.
In fact, i took the liberty and i forked your project and already made the changes, but i guess i need permissions to make a Pull Request.
![image](https://user-images.githubusercontent.com/35530927/108629649-a8483c00-743f-11eb-9b54-6184cdfeee01.png)

**Comment by tinchods93** [comment]
Hello! I would like to work on this issue! 
It would be my first PR and also my first time working with someone elses project, but i think i can help you.

In fact, i took the liberty to start working on it. You can, of course, deny the PR.

**Comment by kishankr7979** [comment]
@sixthcodebrewer If this issue hasn't been resolved yet, the please assign me the same
