### ISSUE TITLE
Addition of code of conduct file

### ISSUE THREAD

**Issue by Sloth-Panda** [GP-Kulam/link-manager#4]
Would like to add code of conduct  and contributing file as part of CWOC

**Comment by sixthcodebrewer** [comment]
Go ahead

**Comment by Sloth-Panda** [comment]
can you add crossWoc tag too @sixthcodebrewer

**Comment by sixthcodebrewer** [comment]
> can you add crossWoc tag too @sixthcodebrewer

Done
