### ISSUE TITLE
Adding Instruction to run the project in readme

### ISSUE THREAD

**Issue by sixthcodebrewer** [GP-Kulam/link-manager#7]
1. include the npm and node version supported.
2. commands how to install the node and run the project.
3. Improve the readme

**Comment by Devenkapoor7303** [comment]
Can I work on it ?

**Comment by Nirbhay1910** [comment]
Hi, Pls assign this issue to me

**Comment by nilisha-jais** [comment]
I want to work on it

**Comment by sixthcodebrewer** [comment]
> Can I work on it ?

Carry on, will assign you the issue soon

**Comment by sixthcodebrewer** [comment]
> Hi, Pls assign this issue to me

Hello, you could create a new issue!
If you would like to add anything to it.

**Comment by Devenkapoor7303** [comment]
Okay

**Comment by sixthcodebrewer** [comment]
> Okay

Could you complete it by tomorrow ?

**Comment by Devenkapoor7303** [comment]
Yeah i will do it tonight sorry for being late
